### ISSUE TITLE
tapping a push notification from the background in iOS doesnt call 'notification' handler

### ISSUE THREAD

**Issue by djett41** [intercom/intercom-cordova#154]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Cordova CLI version - 6.5.0
  - Cordova iOS version - 4.3.1
  - Intercom for Cordova/PhoneGap version: 3.0.26
  - Intercom Push Plugin Fork version: 1.9.2 (although ios code is up to date with master)
  - iOS/Android OS version: ios 10.2
  - iOS/Android Device: iPhone 6s

## Expected behavior
Tapping a push notification from the background should call the notification push handler in JS as well as call openURL and handleOpenURL in native ios/cordova.  
## Actual behavior
Once you tap the push notification while in the background, the app launches but nothing else happens.  Clicking on a push notification while the app is completely killed works as intended, but clicking while app is in the background doesn't work

## Steps to reproduce
 1. Set a breakpoint, log, or alert in your JS PushPlugin notification handler
 2. Have your app in the background and send a push from intercom
 3. tap on the push notification.  The app is opened, but nothing happens (non coldstart).  If you completely kill the app and tap on the notification (coldstart), the handler gets called.  Also confirmed this works on Android

## Logs
This has been a big topic over in the push plugin repo and seems to be related to ios 10+., Some people have resolved the issue by changing the payload structure for the push notifications, which I am unable to do since they are sent from Intercom.  The push plugin added some docs in the README that include the recommended way to send push notification for iOS 10.2.  Some people have pointed to content-available being the culprit, while some have mentioned setting it to 1, true, or even omitting it.  I also confirmed that didReceiveRemoteNotification is called for the push notification, and the isIntercomNotification returns true.  Also the content-available is set to 0 for the push notification that doesn't seem to call notification handler.

Please let me know if you have any questions.  Or would you mind sharing the payload that intercom sends?  Thanks!!

See the following threads/issues for more details
https://github.com/phonegap/phonegap-plugin-push/issues/1629
https://github.com/phonegap/phonegap-plugin-push/issues/1565
https://github.com/phonegap/phonegap-plugin-push/issues/1577
https://github.com/phonegap/phonegap-plugin-push/issues/1265

See the updated README docs here for push payloads
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md

**Comment by jtreanor** [comment]
Hi @djett41,

Thanks for the detailed report. This is very useful. While we are looking into this, could you try using version 3.1.0 of the plugin to see if that helps?

James

**Comment by jtreanor** [comment]
One more thing to try is temporarily removing the PhoneGap push plugin to if it works without that.

**Comment by jtreanor** [comment]
I have tracked down the issue here. It is caused by a conflict between the push plugin and Intercom. We will ship a fix with the next release.

**Comment by Anu2g** [comment]
Thanks as usual, @jtreanor

**Comment by djett41** [comment]
awesome @jtreanor thanks alot!

**Comment by djett41** [comment]
just curious @jtreanor what was the issue you found?  Just wondering because I spent a ton of time debugging and was throwing the kitchen sink at it on my end ha!  I saw your commit to plugin.xml although I verified that was already in ours (comes from push plugins plugin.xml), which didnt seem to resolve our issue, I also have fetch and location as UIBackgroundModes.

Thanks!!

**Comment by jtreanor** [comment]
@djett41 The issue is that the PhoneGap push plugin implements `application:didReceiveRemoteNotification:fetchCompletionHandler:` through a category.
This is an issue because when Intercom initialises push notifications it checks is that method implemented on `AppDelegate`. Since it is not, Intercom adds the method through swizzling. Unfortunately, the push plugin's category then overrides the method we have added.

The changes I'm about to release (waiting for the iOS build to complete) allows iOS push to work safely alongside the push plugin. This means the fork will no longer be necessary for iOS (its still needed for Android for now: https://github.com/phonegap/phonegap-plugin-push/issues/1640).

I'll have a PR here shortly that will illustrate the issue more clearly.

**Comment by jtreanor** [comment]
The fix has now been shipped in [3.1.1](https://github.com/intercom/intercom-cordova/releases/tag/3.1.1) 🎉 

I have also updated our push plugin fork to be compatible with it.

Thanks for reporting the issue 😄

**Comment by djett41** [comment]
aweomse thanks!!!! @jtreanor

**Comment by djett41** [comment]
@jtreanor thanks for tagging this release, can you also tag the push fork?  since we dont commit plugins, its kinda risky referencing master in the config.xml.  Thanks!

**Comment by jtreanor** [comment]
@djett41 Its now tagged with `v1.9.0.1`

**Comment by djett41** [comment]
awesome thanks!

**Comment by jtreanor** [comment]
A quick update: Compatibility with our GCM providers has been fixed in [3.1.2](https://github.com/intercom/intercom-cordova/releases/tag/3.1.2). This means that it is no longer required to use the Intercom fork of `phonegap-plugin-push`,

**Comment by andymurakami** [comment]
Hi .. I´m not understand:  I have update the phonegap-plugin-push or cordova version ? Can you show one tutorial to explain how I make this update ?

I´m have the same problem on IOS, using Ionic 1.

**Comment by RoydenTJames** [comment]
Hi There, I am using version 4 of the intercom plugin and im not using the push-plugin, but I still get the same issue. Push notification handling works as expected after killing the app, but does not work when app is only in the back ground.

My plugin list:
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.1 "Badges"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-intercom 4.0.0 "Intercom"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova.plugins.diagnostic 3.7.1 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by ronocod** [comment]
@RoydenTJames can you open a separate issue for this? This issue is for an iOS issue we already fixed.
