### ISSUE TITLE
App crash after calling intercom.displayConversationsList()

### ISSUE THREAD

**Issue by kinkay716** [intercom/intercom-cordova#78]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.9
  - iOS/Android OS version: Android API23
  - iOS/Android Device: 

## Expected behavior
Should bring up the conversation.  Works fine in iOS.
## Actual behavior
Crashes App.

## Logs

> 09-02 15:31:11.846: E/chromium(13163): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
09-02 15:31:11.920: I/ActivityManager(1518): START u0 {flg=0x10000000 cmp=me.sitter.app/io.intercom.android.sdk.activities.IntercomMessengerActivity (has extras)} from uid 10062 on display 0
09-02 15:31:11.934: W/art(13163): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-02 15:31:11.954: D/AndroidRuntime(13163): Shutting down VM
09-02 15:31:11.954: E/AndroidRuntime(13163): FATAL EXCEPTION: main
09-02 15:31:11.954: E/AndroidRuntime(13163): Process: me.sitter.app, PID: 13163
09-02 15:31:11.954: E/AndroidRuntime(13163): java.lang.RuntimeException: Unable to start activity ComponentInfo{me.sitter.app/io.intercom.android.sdk.activities.IntercomMessengerActivity}: android.view.InflateException: Binary XML file line #44: Binary XML file line #44: Error inflating class android.support.design.widget.FloatingActionButton
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.os.Looper.loop(Looper.java:148)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at java.lang.reflect.Method.invoke(Native Method)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-02 15:31:11.954: E/AndroidRuntime(13163): Caused by: android.view.InflateException: Binary XML file line #44: Binary XML file line #44: Error inflating class android.support.design.widget.FloatingActionButton
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at io.intercom.android.sdk.inbox.ConversationsListFragment.onCreateView(ConversationsListFragment.java:112)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.Activity.performStart(Activity.java:6253)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	... 9 more
09-02 15:31:11.954: E/AndroidRuntime(13163): Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class android.support.design.widget.FloatingActionButton
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	... 22 more
09-02 15:31:11.954: E/AndroidRuntime(13163): Caused by: java.lang.reflect.InvocationTargetException
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at java.lang.reflect.Constructor.newInstance(Native Method)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	... 29 more
09-02 15:31:11.954: E/AndroidRuntime(13163): Caused by: java.lang.NoSuchMethodError: No direct method <init>(Landroid/widget/ImageView;Landroid/support/v7/widget/AppCompatDrawableManager;)V in class Landroid/support/v7/widget/AppCompatImageHelper; or its super classes (declaration of 'android.support.v7.widget.AppCompatImageHelper' appears in /data/app/me.sitter.app-1/base.apk)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:170)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:147)
09-02 15:31:11.954: E/AndroidRuntime(13163): 	... 31 more
09-02 15:31:11.955: W/ActivityManager(1518):   Force finishing activity me.sitter.app/io.intercom.android.sdk.activities.IntercomMessengerActivity
09-02 15:31:11.959: W/ActivityManager(1518):   Force finishing activity me.sitter.app/.MainActivity
09-02 15:31:12.002: D/DropBoxEntryAddedChimeraService(2249): User is not opted-in to Usage & Diagnostics or Lockbox.
09-02 15:31:12.004: I/OpenGLRenderer(1518): Initialized EGL, version 1.4
09-02 15:31:12.460: W/ActivityManager(1518): Activity pause timeout for ActivityRecord{3b58796 u0 me.sitter.app/io.intercom.android.sdk.activities.IntercomMessengerActivity t29 f}
09-02 15:31:17.015: I/Process(13163): Sending signal. PID: 13163 SIG: 9
09-02 15:31:17.025: W/InputDispatcher(1518): channel 'b11e20a me.sitter.app/me.sitter.app.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
09-02 15:31:17.025: E/InputDispatcher(1518): channel 'b11e20a me.sitter.app/me.sitter.app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-02 15:31:17.031: I/WindowState(1518): WIN DEATH: Window{4d4dfb8 u0 SurfaceView}
09-02 15:31:17.031: D/ConnectivityService(1518): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=22, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ], android.os.BinderProxy@b1d8191)
09-02 15:31:17.031: D/ConnectivityService(1518): releasing NetworkRequest NetworkRequest [ id=22, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
09-02 15:31:17.032: D/GraphicsStats(1518): Buffer count: 4
09-02 15:31:17.037: E/ConnectivityService(1518): RemoteException caught trying to send a callback msg for NetworkRequest [ id=22, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
09-02 15:31:17.042: I/WindowState(1518): WIN DEATH: Window{b11e20a u0 me.sitter.app/me.sitter.app.MainActivity}
09-02 15:31:17.042: W/InputDispatcher(1518): Attempted to unregister already unregistered input channel 'b11e20a me.sitter.app/me.sitter.app.MainActivity (server)'
09-02 15:31:17.044: E/Surface(1518): getSlotFromBufferLocked: unknown buffer: 0xa0974930
09-02 15:31:17.047: D/OpenGLRenderer(1518): endAllStagingAnimators on 0x9cd8c800 (RippleDrawable) with handle 0x9e1948b0
09-02 15:31:17.065: I/ActivityManager(1518): Process me.sitter.app (pid 13163) has died
09-02 15:31:17.065: W/ActivityManager(1518): Scheduling restart of crashed service me.sitter.app/io.intercom.android.sdk.gcm.IntercomGcmIntentService in 10246ms
09-02 15:31:17.065: W/ActivityManager(1518): Scheduling restart of crashed service me.sitter.app/com.onesignal.SyncService in 20246ms
09-02 15:31:17.071: W/InputMethodManagerService(1518): Got RemoteException sending setActive(false) notification to pid 13163 uid 10062
09-02 15:31:17.226: W/AppOps(1518): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-02 15:31:27.316: I/art(13760): Not late-enabling -Xcheck:jni (already on)
09-02 15:31:27.325: I/ActivityManager(1518): Start proc 13760:me.sitter.app/u0a62 for service me.sitter.app/io.intercom.android.sdk.gcm.IntercomGcmIntentService
09-02 15:31:27.348: I/MultiDex(13760): VM with version 2.1.0 has multidex support
09-02 15:31:27.348: I/MultiDex(13760): install
09-02 15:31:27.348: I/MultiDex(13760): VM has multidex support, MultiDex support library is disabled.

**Comment by lafactoriafr** [comment]
Hello, same for us. Impossible to user the plugin in Android, crashes the app.

**Comment by ronocod** [comment]
This should be fixed in version 3.0.10. If you can, make sure that your Android build is using the latest version of the Support Library.

**Comment by bboyle18** [comment]
This issue is fixed in release 3.0.10 so I'm going to close it.
Brian

**Comment by lafactoriafr** [comment]
Hello,

Sorry but we're still having the same problem with release 3.0.11 on some Android phones (working on emulator but not on physical device)

Here is the log : 

> E/AndroidRuntime(16107): FATAL EXCEPTION: main
> E/AndroidRuntime(16107): Process: com.pinotbleu.www, PID: 16107
> E/AndroidRuntime(16107): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pinotbleu.www/io.intercom.android.sdk.activities.IntercomMessengerActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
> E/AndroidRuntime(16107): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
> E/AndroidRuntime(16107): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
> E/AndroidRuntime(16107): 	at android.app.ActivityThread.access$900(ActivityThread.java:170)
> E/AndroidRuntime(16107): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
> E/AndroidRuntime(16107): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> E/AndroidRuntime(16107): 	at android.os.Looper.loop(Looper.java:146)
> E/AndroidRuntime(16107): 	at android.app.ActivityThread.main(ActivityThread.java:5635)
> E/AndroidRuntime(16107): 	at java.lang.reflect.Method.invokeNative(Native Method)
> E/AndroidRuntime(16107): 	at java.lang.reflect.Method.invoke(Method.java:515)
> E/AndroidRuntime(16107): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
> E/AndroidRuntime(16107): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
> E/AndroidRuntime(16107): 	at dalvik.system.NativeStart.main(Native Method)
> E/AndroidRuntime(16107): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
> E/AndroidRuntime(16107): 	at android.content.res.Resources.loadDrawable(Resources.java:3439)
> E/AndroidRuntime(16107): 	at android.content.res.Resources.getDrawable(Resources.java:1893)
> E/AndroidRuntime(16107): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
> E/AndroidRuntime(16107): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
> E/AndroidRuntime(16107): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
> E/AndroidRuntime(16107): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
> E/AndroidRuntime(16107): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
> E/AndroidRuntime(16107): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
> E/AndroidRuntime(16107): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
> E/AndroidRuntime(16107): 	at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:19)
> E/AndroidRuntime(16107): 	at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:64)
> E/AndroidRuntime(16107): 	at android.app.Activity.performCreate(Activity.java:5580)
> E/AndroidRuntime(16107): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
> E/AndroidRuntime(16107): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
> E/AndroidRuntime(16107): 	... 11 more
> E/AndroidRuntime(16107): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
> E/AndroidRuntime(16107): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
> E/AndroidRuntime(16107): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
> E/AndroidRuntime(16107): 	at android.content.res.Resources.loadDrawable(Resources.java:3435)
> E/AndroidRuntime(16107): 	... 31 more
> W/Settings( 2415): Setting dropbox_age_seconds has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
> W/ActivityManager( 2415):   Force finishing activity com.pinotbleu.www/io.intercom.android.sdk.activities.IntercomMessengerActivity

Thanks in advance for you help.

**Comment by ronocod** [comment]
What version of Android is the device running? Can you do a full clean build and see if the issue still happens?

**Comment by lafactoriafr** [comment]
I started a clean project with only Intercom, still bugging.

It bugs on Android 4.4 and below.

Thanks.

**Comment by ronocod** [comment]
We can't reproduce this in our Example app which is here: https://github.com/intercom/intercom-cordova/tree/master/Example

Is there any Android-specific settings in your `config.xml` file which could be affecting this?

**Comment by lafactoriafr** [comment]
Unfortunately, your example app doesn't work neither here. My Android support library is up to date.

It seems that the problem is related to a resource not found, so maybe it could be related to the way we build the app. We just use 'ionic build android'. Do you do the same?

Thanks

![capture d ecran 2016-09-21 a 18 22 36](https://cloud.githubusercontent.com/assets/4179479/18719635/7368c190-8028-11e6-9f7e-22bc42ffc060.png)

**Comment by ronocod** [comment]
No, we don't use Ionic at all. Our build steps are in the `README.md` file in the example project folder I linked above.

**Comment by lafactoriafr** [comment]
Sorry, I meant cordova run android.

**Comment by lafactoriafr** [comment]
Do you need any other information to try to find the bug?

**Comment by ronocod** [comment]
Can you open a separate issue for this? It seems to be different from the original issue in this thread. We'll keep investigating your bug.

**Comment by lafactoriafr** [comment]
Ok, done. Thanks.

**Comment by pointiitm** [comment]
Hi. I am also facing this issue. Any solution yet?

**Comment by Compulsed** [comment]
Same problem but with this error

```
 Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
``` 

This Happens when I open the intercom messenger, or any other native component view
